// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI02p4aQF_nbKgRjG_uH-sSDnOMrMbBpk',
    appId: '1:665774794503:web:5a5222d24a21cc5fe807a2',
    messagingSenderId: '665774794503',
    projectId: 'chat-app-4da79',
    authDomain: 'chat-app-4da79.firebaseapp.com',
    storageBucket: 'chat-app-4da79.firebasestorage.app',
    measurementId: 'G-98MYLVHRM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76SGRNXAzXC_LeCnoXeQYdTl_039zKzg',
    appId: '1:665774794503:android:9a0bf1d97832ddf8e807a2',
    messagingSenderId: '665774794503',
    projectId: 'chat-app-4da79',
    storageBucket: 'chat-app-4da79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCINEr6jJ--2hJleUfr93pAfFuP1MHl49o',
    appId: '1:665774794503:ios:88c686878df8836ae807a2',
    messagingSenderId: '665774794503',
    projectId: 'chat-app-4da79',
    storageBucket: 'chat-app-4da79.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCINEr6jJ--2hJleUfr93pAfFuP1MHl49o',
    appId: '1:665774794503:ios:88c686878df8836ae807a2',
    messagingSenderId: '665774794503',
    projectId: 'chat-app-4da79',
    storageBucket: 'chat-app-4da79.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI02p4aQF_nbKgRjG_uH-sSDnOMrMbBpk',
    appId: '1:665774794503:web:1a47e2bdd092d2d8e807a2',
    messagingSenderId: '665774794503',
    projectId: 'chat-app-4da79',
    authDomain: 'chat-app-4da79.firebaseapp.com',
    storageBucket: 'chat-app-4da79.firebasestorage.app',
    measurementId: 'G-9BE2M1PLVV',
  );
}
